(in-package #:frob)

;;;; -- Test Entry --

(-> run-tests () boolean)
(defun run-tests ()
  "Run Frob's dependency-free unit tests and return true on success."
  (setf *test-count* 0)
  (let ((configuration (configuration-create
                        :source-root (asdf:system-source-directory :frob)
                        :working-directory (asdf:system-source-directory :frob))))
    (test-assert (string= (configuration-model configuration) "gpt-5.6-sol")
                 "the default model is gpt-5.6-sol")
    (test-assert (string= (configuration-reasoning-effort configuration) "ultra")
                 "the default reasoning effort is ultra")
    (test-assert (string= (configuration-wire-effort configuration) "max")
                 "ultra maps to the provider max effort")
    (test-assert (= (json-get (json-object "answer" 42) "answer") 42)
                 "JSON object access preserves values")
    (test-assert (vectorp (json-decode "[1,2,3]"))
                 "JSON arrays have one consistent vector representation")
    (test-assert (search (system-prompt--current-date)
                         (system-prompt configuration))
                 "the system prompt carries the current date")
    (test-conversation-persistence)
    (test-authentication-store)
    (test-authentication-bootstrap-and-refresh)
    (test-provider-request)
    (test-provider-stream-decoding)
    (test-provider-stream-failures)
    (test-provider-authentication-retries)
    (test-tool-registry)
    (test-lisp-worker-protocol)
    (test-self-tools)
    (test-durable-self-mutation)
    (test-generation-manifest)
    (test-crash-capsule-correlation)
    (run-device-authentication-tests)
    (run-agent-tests)
    (run-terminal-tests)
    (run-markdown-tests)
    (run-application-tests))
  (format t "~&~:D Frob tests passed.~%" *test-count*)
  t)
