(in-package #:autolith)

;;;; -- Test Entry --

(-> run-tests () boolean)
(defun run-tests ()
  "Run Autolith's dependency-free unit tests and return true on success."
  (setf *test-count* 0)
  (let ((configuration (configuration-create
                        :source-root (asdf:system-source-directory :autolith)
                        :working-directory (asdf:system-source-directory :autolith))))
    (test-assert (string= (configuration-model configuration) "gpt-5.6-sol")
                 "the default model is gpt-5.6-sol")
    (test-assert (string= (configuration-model
                           (configuration-with-model configuration
                                                     "gpt-5.6-luna"))
                          "gpt-5.6-luna")
                 "model copies swap only the model")
    (test-assert (= (configuration-context-window configuration) 272000)
                 "5.6 models carry the live catalog context window")
    (test-assert (= (configuration-context-window
                     (configuration-with-model configuration "gpt-5.6-terra"))
                    272000)
                 "model copies recompute the context window")
    (test-assert (= (configuration-compaction-token-limit configuration)
                    217600)
                 "compaction triggers at the threshold share of the window")
    (test-assert (handler-case
                     (progn
                       (configuration-with-model configuration "gpt-4")
                       nil)
                   (configuration-error ()
                     t))
                 "model copies reject identifiers outside the 5.6 family")
    (let ((moved (configuration-with-working-directory configuration "tests")))
      (test-assert
       (equal (configuration-working-directory moved)
              (truename (merge-pathnames "tests/"
                                         (configuration-working-directory
                                          configuration))))
       "working-directory copies resolve relative existing directories")
      (test-assert
       (equal (configuration-source-root moved)
              (configuration-source-root configuration))
       "working-directory copies preserve unrelated configuration"))
    (test-assert
     (handler-case
         (progn
           (configuration-with-working-directory configuration "README.org")
           nil)
       (working-directory-error (condition)
         (eq (working-directory-error-stage condition) ':validation)))
     "working-directory copies reject files with a structured condition")
    (test-assert (string= (configuration-reasoning-effort configuration) "ultra")
                 "the default reasoning effort is ultra")
    (test-assert (not (configuration-immutable-p configuration))
                 "ordinary configuration enables active-image mutation tools")
    (test-assert
     (configuration-immutable-p
      (configuration-with-model
       (configuration--clone configuration :immutable-p t)
       "gpt-5.6-luna"))
     "configuration clones preserve immutable mode")
    (test-assert (string= (configuration-wire-effort configuration) "max")
                 "ultra maps to the provider max effort")
    (test-assert
     (string= (configuration-wire-effort
               (configuration-with-reasoning-effort configuration "none"))
              "none")
     "none is passed through as a provider reasoning effort")
    (test-assert (= (json-get (json-object "answer" 42) "answer") 42)
                 "JSON object access preserves values")
    (test-assert (vectorp (json-decode "[1,2,3]"))
                 "JSON arrays have one consistent vector representation")
    (test-memory-persistence)
    (test-user-init)
    (test-memory-tools)
    (test-agenda-persistence-and-transport)
    (test-agenda-command)
    (test-agenda-version-one-migration)
    (test-agenda-malformed-state)
    (test-agenda-tools-and-prompt)
    (test-preferences)
    (test-command-permission-persistence)
    (test-command-permission-corruption)
    (test-later-persistence)
    (test-later-malformed-state)
    (test-later-reset-selection)
    (test-system-prompt-context)
    (test-request-local-context)
    (test-conversation-persistence)
    (test-conversation-origin-directory)
    (test-conversation-model-selection)
    (test-conversation-compaction)
    (test-authentication-store)
    (test-authentication-bootstrap-and-refresh)
    (test-provider-request)
    (test-provider-rate-limits)
    (test-provider-stream-decoding)
    (test-provider-stream-failures)
    (test-provider-authentication-retries)
    (test-tool-registry)
    (test-workspace-tools)
    (test-search-tools)
    (test-lisp-image-manifests)
    (test-lisp-worker-protocol)
    (test-lisp-worker-image-snapshot)
    (test-self-tools)
    (test-self-restart-selection)
    (test-self-discard)
    (test-durable-self-mutation)
    (test-generation-manifest)
    (test-active-image-build-record)
    (test-image-commit-replay-probe)
    (test-crash-capsule-correlation)
    (run-device-authentication-tests)
    (run-agent-tests)
    (test-task-orchestration)
    (run-terminal-tests)
    (run-layout-tests)
    (run-markdown-tests)
    (test-release-scripts)
    (test-release-server)
    (run-application-tests))
  (format t "~&~:D Autolith tests passed.~%" *test-count*)
  t)
